helmDefaults:
  wait: true
  createNamespace: true

repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    chart: argo/argo-cd
    namespace: argocd
  
  - name: argocd-apps
    chart: argo/argocd-apps
    namespace: argocd
    values:
      - ./values/argocd-apps.yaml