apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namespace.name }}-app
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.namespace.name }}
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: {{ index .Values "prometheus-node-exporter" "source" "url" }}
    targetRevision: {{ index .Values "prometheus-node-exporter" "source" "targetRevision" }}
    path: {{ index .Values "prometheus-node-exporter" "source" "path" }}
    helm:
      releaseName: "prometheus-node-exporter"
      {{- with .Values.application }}
      values: |
        {{- unset . "source" | toYaml | nindent 8 }}
      {{- end }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: -1
