apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: filebrowser
  name: {{ .Values.namespace.name }}-app
spec:
  selector:
    matchLabels:
      app: {{ .Values.namespace.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.namespace.name }}
    spec:
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:v2.42.5
          volumeMounts:
{{ toYaml .Values.volumeMounts | indent 12 }}