apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namespace.name }}-service
  labels:
    app: {{ .Values.namespace.name }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.namespace.name }}
