apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami-root-app
  namespace: "argocd"
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  destination:
    namespace: "argocd"
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: whoami
      values: |-
        waves:
          project: 100
          rootApplication: 200
          namespace: 300
          application: 400
      valueFiles: 
        - values.yaml
    repoURL: https://github.com/Invasor-de-Fronteiras/homelab.git
    targetRevision: HEAD
    path: apps/whoami
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 1 