namespaces:
  - name: cloudflare-tunnel

apps:
  - name: whoami
    source:
      releaseName: whoami
      targetRevision: HEAD
      url: https://github.com/Invasor-de-Fronteiras/homelab.git
      path: ./apps/whoami
    destination:
      namespace: argocd
  - name: argocd
    source:
      releaseName: argocd
      targetRevision: HEAD
      url: https://github.com/Invasor-de-Fronteiras/homelab.git
      path: ./apps/argocd
    destination:
      namespace: argocd
  - name: cloudflare-tunnel
    source:
      releaseName: cloudflare-tunnel
      targetRevision: HEAD
      url: https://github.com/Invasor-de-Fronteiras/homelab.git
      path: ./apps/cloudflare-tunnel
    destination:
      namespace: cloudflare-tunnel
  - name: traefik
    source:
      releaseName: traefik
      targetRevision: HEAD
      url: https://github.com/Invasor-de-Fronteiras/homelab.git
      path: ./apps/traefik
    destination:
      namespace: kube-system