apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: filebrowser
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy.svc:80/oauth2/auth
    authResponseHeaders: Authorization
    trustForwardHeader: true
