apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: filebrowser
spec:
  forwardAuth:
    address: https://auth.arcamh.com/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - "Authorization"
      - "X-Auth-Request-Access-Token"
