apiVersion: v1
kind: PersistentVolume
metadata:
  name: kelbi-pg-volume
  labels:
    app: kelbi-pg
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/kelbi/postgresql