apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kelbi-debug-app
  namespace: "argocd"
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  destination:
    namespace: "kelbi-debug"
    server: https://kubernetes.default.svc
  project: "default"
  source:
    repoURL: https://github.com/Invasor-de-Fronteiras/helm-charts
    targetRevision: HEAD
    path: charts/kelbi
    helm:
      release: kelbi-debug
      valuesObject:
        global:
          secretName: debug-kelbi-database-secret
          host: 89.116.225.172
        postgresql:
          enabled: false
        patchServer:
          en: "en-patch.arcamh.com"
          jp: "jp-patch.arcamh.com"
        entriesServer:
          volumes:
            - name: "bin"
              hostPath:
                path: "/root/volumes/bin"
                type: Directory
          volumeMounts:
            - name: "bin"
              mountPath: "/app/bin"
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 1