apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kelbi-debug-app
  namespace: "argocd"
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  destination:
    namespace: "argocd"
    server: https://kubernetes.default.svc
  project: "default"
  source:
    repoURL: https://github.com/Invasor-de-Fronteiras/helm-charts
    targetRevision: HEAD
    path: charts/kelbi
    helm:
      release: kelbi-debug
      valuesObject:
        postgresql:
          enabled: false
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 15s
        factor: 1