apiVersion: v1
kind: Secret
metadata:
  name: debug-kelbi-database-secret
type: Opaque
data:
  ERUPE_DATABASE_HOST: {{ }}
  ERUPE_DATABASE_USER: {{ .Values.postgresql.global.postgresql.auth.username | b64enc | quote }}
  ERUPE_DATABASE_PASSWORD: {{ .Values.postgresql.global.postgresql.auth.password | b64enc | quote }}
