apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.name }}-server
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - websecure
    - web
  routes:
    {{- range $serverIndex, $server := .Values.patchservers }}
    - kind: Rule
      match: Host(`{{ $server.ingress.host }}`)
      priority: 10
      services:
        - name: {{ $.Values.name }}-{{ $server.name }}-service
          namespace: {{ $.Values.namespace }}
          port: 80
    {{- end -}}