{{- $values := .Values -}}
{{- range $serverIndex, $server := .Values.patchservers }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $values.name }}-{{ $server.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ $values.name }}-{{ $server.name }}-service
spec:
  type: {{ $server.service.type }}
  ports:
    - port: {{ $server.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ $values.name }}-{{ $server.name }}
{{- end -}}
