apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-addons
  sources:
    # - repoURL: https://github.com/argoproj/argo-cd
    #   path: manifests/crds
    #   targetRevision: v3.3.2
    - repoURL: 'https://argoproj.github.io/argo-helm'
      targetRevision: 9.1.4
      chart: argo-cd
      helm:
        valuesObject:
          global:
            domain: https://argocd.arcamh.com
            logging:
              level: debug
          configs:
            secret:
              githubSecret:
            rbac:
              "policy.csv": |
                p, role:admin, exec, create, */*, allow
                g, Invasor-de-Fronteiras:devops, role:admin
            params:
              server.insecure: true
            cm:
              exec.enabled: true
              url: https://argocd.arcamh.com
              dex.config: |
                connectors:
                  - type: github
                    id: github
                    name: GitHub
                    config:
                      clientID: aa545d98348387861211
                      clientSecret: $argocd-dex-secret:dex.github.clientSecret
                      orgs:
                      - name: Invasor-de-Fronteiras
                      scopes:
                      - profile
                      - email
                      - groups
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 3
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - kind: Rule
      match: Host(`argocd.arcamh.com`)
      priority: 10
      services:
        - name: argocd-server
          namespace: argocd
          port: 80
    - kind: Rule
      match: Host(`argocd.arcamh.com`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          namespace: argocd
          port: 80
          scheme: h2c
  # tls: {}
  #   certResolver: default