apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-addons-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-addons
  source:
    repoURL: 'https://github.com/Invasor-de-Fronteiras/homelab'
    targetRevision: HEAD
    path: ./cluster-addons/apps
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 3