apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/Invasor-de-Fronteiras/homelab'
    - 'https://github.com/kubernetes-sigs/gateway-api'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
