apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kelbi-app-of-app
  namespace: argocd
spec:
  project: kelbi-apps
  source:
    path: apps/**/**/application.yaml
    repoURL: https://github.com/Invasor-de-Fronteiras/kelbi-applications.git
    targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
