apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kelbi-applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/Invasor-de-Fronteiras/kelbi-applications.git
        revision: main
        files:
          - path: 'apps/**/**/values.yaml'
        values:
          env: '{{ index .path.segments 1 }}'
          app: '{{ index .path.segments 2 }}'
  template:
    metadata:
      name: '{{.values.env}}-{{.values.app}}'
    spec:
      project: kelbi-apps
      sources:
        - ref: repo
          repoURL: https://github.com/Invasor-de-Fronteiras/kelbi-applications.git
          targetRevision: main

        - repoURL: https://github.com/Invasor-de-Fronteiras/homelab.git
          targetRevision: HEAD
          path: charts/kelbi-app
          helm:
            values: |
              httpRoute:
                parents:
                  - name: traefik-gateway
                    sectionName: web
                    kind: Gateway
                    port: 8000
                    namespace: traefik
            valueFiles:
              - $repo/{{.path.path}}/values.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: apps

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
