apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: default
  source:
    chart: oauth2-proxy
    targetRevision: 7.7.6
    repoURL: "https://oauth2-proxy.github.io/manifests"
    helm:
      values: |
        alphaConfig:
          enabled: true
          existingSecret: oauth2-proxy-secret
  destination:
    namespace: oauth2-proxy
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
