apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: {{ .Values.argocd.global.domain }}
  statusbadge.enabled: "true"
  statusbadge.url: "https://cd-status.apps.argoproj.io/"
  users.anonymous.enabled: "false"
  admin.enabled: "true"
  users.session.duration: "24h"
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: aa545d98348387861211
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: Invasor-de-Fronteiras