apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingressroute
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:             
  - kind: Rule
    match: Host(`argocd.infra.arcamh.com`)
    services:
    - kind: Service
      name: traefik
      namespace: kube-system
