namespace:
  name: argocd
 
application:
  source:
    chart: argo-cd
    url: https://argoproj.github.io/argo-helm
    targetRevision: 9.4.5
  global:
    logging:
      level: debug
    domain: https://argocd.arcamh.com
  configs:
    secret:
      githubSecret:
    rbac:
      "policy.csv": |
        p, role:admin, exec, create, */*, allow
        g, Invasor-de-Fronteiras:devops, role:admin
    params:
      server.insecure: true
    cm:
      exec.enabled: true
      url: https://argocd.arcamh.com
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: aa545d98348387861211
              clientSecret: $argocd-dex-secret:dex.github.clientSecret
              orgs:
              - name: Invasor-de-Fronteiras
              scopes:
              - profile
              - email
              - groups